### ISSUE TITLE
5./node/show質問の表示 + 回答の追加(5.1)

### ISSUE THREAD

**Issue by Aa0175** [Aa0175/pf2#30]
元: [#25 ](https://github.com/Aa0175/pf2/issues/25)
- [ ] /question/show内で非同期処理でnodes#new_aできるようにする #49 
- [ ] ページ遷移なしで次々質問と回答を表示させる#51
- [x] 最後の回答選択後に/posts/showに飛ぶ機能追加 #52
- [ ] nodes#new(両方)の追加数制限と入れ替え順序の制限 #50
- [ ] ページのタイトルはpostのtitleにする

これ使えばpost/show内で全部見れる？（例えば@post.nodesとか）[参考](https://qiita.com/rok/items/b8de8549aa62a16d64f1)
