### ISSUE TITLE
13./posts/new　新規投稿(さらに/nodes/new_q→/nodes/new_aへと遷移)

### ISSUE THREAD

**Issue by Aa0175** [Aa0175/pf2#38]
元: #25
### タスク
- [x] 投稿済みpostに追加で新規投稿する機能 #42
- [ ] 一つのnode_qが持てるnode_aの数を4つに制限する #43
- [x] 複数質問・回答を投稿できる機能 #44
- [ ] 任意の質問･回答に子ノードを追加できる機能
- [ ] posts/new→nodes/new_q→nodes/new_aの流れ中にバックリンクで一つ前の再編集ができるようにする
- [ ] パンくずリスト機能の追加 #64 
- [ ] フォルダツリーライクにpost内のQ/Aを表示できるようにする機能追加 #65 
- [ ] 各投稿時、空のまま投稿を押すとそのまま/nodesにリダイレクトさせる　関連: #72 
- [ ] posts/newからシームレスにnodes/new_q、nodes/new_aも入力できるよう修正　#9 
- [ ] 同じpost/:id内でシームレスに次の質問が表示されるようにする
- [ ] Viewを整える
